version: "3"
services:
    server:
        container_name: server-live
        restart: always
        build: .
        ports:
            - "3001:3005"
            - "8000:8000"
            - "1935:1935"
