#the docker compose file version
version: "3.7"
# you can run multiple services inside one docker compose file
# define them with their dependencies one after the other
services:
    # service 1 named react-prod
    web-app:
        # service 1 container name
        container_name: web-app
        build: .
        ports:
            - "8001:8001"
